Main setup
ZsomborHajzer/Project-DAM pull request #12
Opened 2022-12-14 14:19 UTC by 2560p

This pull request proposes a new root structure.
Everything that can be accessed directly by the end-user is located under `public/` folder. This includes (as for the moment) `images/` and `phpmyadmin/`. 
Any other things that an end-user can make use of not in a direct way (as for example - header and footer elements of every page) are located in `components/`.
File structure might be a subject to change in future, but as far as I am concerned, the current setup completely fits current needs.

2022-12-14 14:25 UTC, ZsomborHajzer approved these changes

2022-12-14 14:25 UTC, ZsomborHajzer commented on public/index.php
> +
GOOD WORK 💯

2022-12-14 14:42 UTC, AlvesBernardo requested changes
Please no index file inside. And maybe add a HTML and PHP folder

2022-12-15 12:25 UTC, AlvesBernardo approved these changes

2022-12-16 09:42 UTC, merged