Home page
ZsomborHajzer/Project-DAM pull request #5
Opened 2022-12-09 13:16 UTC by HakanEgeOzerol

Added comments to css, changed px values to vw, minor adjustments to picture sizes.

2022-12-09 13:18 UTC, HakanEgeOzerol commented
Added comments to css, changed px values to vw, minor adjustments to picture sizes.

2022-12-09 14:32 UTC, AlvesBernardo requested changes

2022-12-09 14:32 UTC, AlvesBernardo commented on projectstyle.css
you are still calling Bannertitle here it should be bannerTitle no?

2022-12-09 14:32 UTC, AlvesBernardo commented on projectstyle.css
> +
same should it not be picture?

2022-12-09 14:32 UTC, AlvesBernardo commented on projectstyle.css
>  #Rightpicture > img {
same here with the Rightpicture

2022-12-09 14:32 UTC, AlvesBernardo commented on projectstyle.css
> -
go over with the names on the css first letter should not be big

2022-12-12 21:48 UTC, AlvesBernardo approved these changes

2023-01-02 14:57 UTC, merged